const express = require('express');
const authRoutes = require('./modules/auth/auth.routes');
const productRoutes = require('./modules/products/products.routes');
const reviewRoutes = require('./modules/reviews/reviews.routes');
const orderRoutes = require('./modules/orders/orders.routes');
const cartRoutes = require('./modules/cart/cart.routes');
const checkoutRoutes = require('./modules/checkout/checkout.routes');
const errorHandler = require('./middleware/errorHandler');

const app = express();
app.disable('x-powered-by');
app.use(express.json({ limit: '1mb' }));
app.get('/health', (_req, res) => res.json({ status: 'ok', service: 'api-load-testing' }));
app.use('/api/auth', authRoutes);
app.use('/api/products', reviewRoutes);
app.use('/api/products', productRoutes);
app.use('/api/orders', orderRoutes);
app.use('/api/cart', cartRoutes);
app.use('/api/checkout', checkoutRoutes);
app.use((_req, res) => res.status(404).json({ error: { code: 404, message: 'Route not found' } }));
app.use(errorHandler);
module.exports = app;
